Use context manager for writing Makefile
TestSuite failing on Linux:
FAILED test_all.py::test_quartus035 - FileNotFoundError: [Errno 2] No such file or directory: '035quartus_err/Makefile'
FAILED test_all.py::test_quartus036 - FileNotFoundError: [Errno 2] No such file or directory: '036quartus_err/Makefile'
FAILED test_all.py::test_quartus037 - FileNotFoundError: [Errno 2] No such file or directory: '037quartus_err/Makefile'
FAILED test_all.py::test_quartus038 - FileNotFoundError: [Errno 2] No such file or directory: '038quartus_err/Makefile'

Probably this is because these testases SHALL NOT generate a valid
makefile.
Before 'atomizing' the Makefile write, these Makefiles have been
generated anyway, despite the detected and reported errors.